#!/bin/bash
echo "#### STARTING AVERAGE SCORE BY AUTHOR - NO COMBINER ####" > run_remaining_jobs.log;
run_average_score_author.sh >> run_remaining_jobs.log;
echo "#### STARTING AVERAGE SCORE BY AUTHOR - WITH COMBINER ####" >> run_remaining_jobs.log;
run_average_score_combiner_author.sh >> run_remaining_jobs.log;
#echo "#### STARTING AVERAGE SCORE BY SUBREDDIT - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_average_score_combiner_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING AVERAGE SCORE BY SUBREDDIT - NO COMBINER ####" >> run_remaining_jobs.log;
#run_average_score_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILDED BY AUTHOR - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_gilded_sorter_combiner_group_by_author.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILDED BY SUBREDDIT - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_gilded_sorter_combiner_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILDED BY AUTHOR - NO COMBINER ####" >> run_remaining_jobs.log;
#run_gilded_sorter_group_by_author.sh >> run_remaining_jobs.log;
#echo "#### STARTGIN GILDED BY SUBREDDIT - NO COMBINER ####" >> run_remaining_jobs.log;
#run_gilded_sorter_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILDED TOTAL - NO COMBINER ####" >> run_remaining_jobs.log;
#run_gilded_sorter.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILD PERCENT BY AUTHOR - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_gild_percent_combiner_group_by_author.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILD PERCENT BY SUBREDDIT - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_gild_percent_combiner_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILD PERCENT BY AUTHOR - NO COMBINER ####" >> run_remaining_jobs.log;
#run_gild_percent_group_by_author.sh >> run_remaining_jobs.log;
#echo "#### STARTING GILD PERCENT BY SUBREDDIT - NO COMBINER ####" >> run_remaining_jobs.log;
#run_gild_percent_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING VOTES BY AUTHOR - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_vote_sorter_combiner_group_by_author.sh >> run_remaining_jobs.log;
#echo "#### STARTING VOTES BY SUBREDDIT - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_vote_sorter_combiner_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING VOTES BY AUTHOR - NO COMBINER ####" >> run_remaining_jobs.log;
#run_vote_sorter_group_by_author.sh >> run_remaining_jobs.log;
#echo "#### STARTING VOTES BY SUBREDDIT - NO COMBINER ####" >> run_remaining_jobs.log;
#run_vote_sorter_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING VOTES ALL - NO COMBINER ####" >> run_remaining_jobs.log;
#run_vote_sorter.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF AUTHORS BY SUBREDDIT - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_wc_author_combiner_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF AUTHORS BY SUBREDDIT - NO COMBINER ####" >> run_remaining_jobs.log;
#run_wc_author_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF ACRONYMS BY SUBREDDIT - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body_acronyms_combiner_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF ACRONYMS ALL - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body_acronyms_combiner.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF ACRONYMS BY SUBREDDIT - NO COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body_acronyms_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF ACRONYMS ALL - NO COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body_acronyms.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF BODY WORDS BY SUBREDDIT - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body_combiner_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF BODY WORDS ALL - WITH COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body_combiner.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF BODY WORDS BY SUBREDDIT - NO COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body_group_by_subreddit.sh >> run_remaining_jobs.log;
#echo "#### STARTING COUNT OF BODY WORDS ALL - NO COMBINER ####" >> run_remaining_jobs.log;
#run_wc_body.sh >> run_remaining_jobs.log;

